# Generated by Django 4.0.4 on 2022-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feelings_action', models.TextField(max_length=120, null=True)),
                ('tendencies', models.TextField(max_length=40, null=True)),
                ('mLocationRequest_result', models.TextField(max_length=50, null=True)),
                ('facial_result', models.TextField(max_length=50, null=True)),
                ('final_result', models.TextField(max_length=120, null=True)),
            ],
        ),
    ]
