# Generated by Django 4.0.4 on 2022-06-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('feelings_action', models.TextField(max_length=100, null=True)),
                ('tendencies', models.TextField(max_length=100, null=True)),
                ('mLocationRequest_result', models.TextField(max_length=150, null=True)),
                ('facial_result', models.TextField(max_length=100, null=True)),
                ('final_result', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
