# Generated by Django 4.0.4 on 2022-06-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feelings_action', models.TextField(max_length=100, null=True)),
                ('facial_result', models.TextField(max_length=100, null=True)),
                ('final_result', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BigData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendencies', models.TextField(max_length=100, null=True)),
                ('final_result', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
